[INFO     2012-03-21 16:34:28,754 bulkloader.py] Logging to bulkloader-log-20120321.163428
[INFO     2012-03-21 16:34:28,755 bulkloader.py] Throttling transfers:
[INFO     2012-03-21 16:34:28,755 bulkloader.py] Bandwidth: 250000 bytes/second
[INFO     2012-03-21 16:34:28,755 bulkloader.py] HTTP connections: 8/second
[INFO     2012-03-21 16:34:28,755 bulkloader.py] Entities inserted/fetched/modified: 20/second
[INFO     2012-03-21 16:34:28,755 bulkloader.py] Batch Size: 10
[INFO     2012-03-21 16:34:28,755 bulkloader.py] Opening database: bulkloader-progress-20120321.163428.sql3
[INFO     2012-03-21 16:34:29,193 bulkloader.py] Opening database: bulkloader-results-20120321.163428.sql3
[DEBUG    2012-03-21 16:34:29,511 adaptive_thread_pool.py] [WorkerThread-0] WorkerThread: started
[DEBUG    2012-03-21 16:34:29,512 adaptive_thread_pool.py] [WorkerThread-1] WorkerThread: started
[DEBUG    2012-03-21 16:34:29,512 adaptive_thread_pool.py] [WorkerThread-2] WorkerThread: started
[DEBUG    2012-03-21 16:34:29,513 adaptive_thread_pool.py] [WorkerThread-3] WorkerThread: started
[DEBUG    2012-03-21 16:34:29,513 adaptive_thread_pool.py] [WorkerThread-4] WorkerThread: started
[DEBUG    2012-03-21 16:34:29,513 adaptive_thread_pool.py] [WorkerThread-5] WorkerThread: started
[DEBUG    2012-03-21 16:34:29,514 adaptive_thread_pool.py] [WorkerThread-6] WorkerThread: started
[DEBUG    2012-03-21 16:34:29,515 adaptive_thread_pool.py] [WorkerThread-7] WorkerThread: started
[DEBUG    2012-03-21 16:34:29,515 adaptive_thread_pool.py] [WorkerThread-8] WorkerThread: started
[DEBUG    2012-03-21 16:34:29,515 adaptive_thread_pool.py] [WorkerThread-9] WorkerThread: started
[DEBUG    2012-03-21 16:34:29,516 bulkloader.py] Configuring remote_api. url_path = /_ah/remote_api, servername = 18.cometiphrd.appspot.com
[DEBUG    2012-03-21 16:34:29,517 bulkloader.py] Bulkloader using app_id: s~cometiphrd
[INFO     2012-03-21 16:34:29,518 bulkloader.py] Connecting to 18.cometiphrd.appspot.com/_ah/remote_api
[INFO     2012-03-21 16:34:52,843 bulkloader.py] Authentication Failed
